### ISSUE TITLE
Should the convolution layers have biases?

### ISSUE THREAD

**Issue by liuyipei** [KaimingHe/deep-residual-networks#10]
This is so helpful! Looking at the prototxt, I have a very quick question about whether the convolution layers should have non-0 bias terms.

Regarding the bias terms in your convolutions, the paper says that "biases are omitted for simplifying notations" which suggested that there should be biases, but you didn't bother writing them down. However, in this published prototxt, I see that bias_term:false in the convolution_params (excluding conv1).

Hence I am just looking for a clarification or a few words in general:  which was/is the intent? Is there a bug?

Thanks in advance!

**Comment by KaimingHe** [comment]
Biases are in the BN layers that follow.

**Comment by erichuang0771** [comment]
Recently, I am converting this caffe model to Tensorpack model and I found that the conv1 in resnet-50 has bias term, however the resnet-101 and resnet-152 do not have bias in conv1. I don't think bias is necessary, since there are BN layers. Any reason?

**Comment by lucasjinreal** [comment]
I have seen lots of different resnet50 versions in terms of caffe prototxt. Some of with bias all true in conv some are not. Those with bias true were always without BatchNorm.

**Comment by ibmua** [comment]
This is not fully applicable to the newer BN-ReLU-Conv-BN-ReLU-Conv architectures, though, as those don't end with a BN.
