### ISSUE TITLE
fine-tuning Res50 on caffe

### ISSUE THREAD

**Issue by liam0949** [KaimingHe/deep-residual-networks#39]
when I was fine-tuning Kaiming's pre-trained model of ResNet50 which was download from the link given, there came up with an error:
I0113 18:32:41.627681    22 net.cpp:110] Creating Layer res2a_branch1
I0113 18:32:41.627684    22 net.cpp:448] res2a_branch1 <- pool1_pool1_0_split_0
I0113 18:32:41.627688    22 net.cpp:419] res2a_branch1 -> res2a_branch1
I0113 18:32:41.628553    22 net.cpp:160] Setting up res2a_branch1
I0113 18:32:41.628568    22 net.cpp:167] Top shape: 32 256 56 56 (25690112)
I0113 18:32:41.628571    22 net.cpp:175] Memory required for data: 610140288
F0113 18:32:41.628585    22 net.cpp:179] Check failed: param_size <= num_param_blobs (2 vs. 1) Too many params specified for layer res2a_branch1
*** Check failure stack trace: *** 
And this is my prototxt:
layer {
	bottom: "pool1"
	top: "res2a_branch1"
	name: "res2a_branch1"
	type: "Convolution"
	convolution_param {
		num_output: 256
		kernel_size: 1
		pad: 0
		stride: 1
		bias_term: false
	}
	param {
      		  lr_mult: 0
    		}
    param { 
      		  lr_mult: 0
    	    }
}

**Comment by simbaforrest** [comment]
I just got the same error, turns out that you should remove the last param, since there are no bias term.

**Comment by liam0949** [comment]
@simbaforrest thank you
