### ISSUE TITLE
resnet50 target_blobs.size() == source_layer.blobs_size() (1 vs. 2)

### ISSUE THREAD

**Issue by billhhh** [KaimingHe/deep-residual-networks#54]
I have the problem:
Check failed: target_blobs.size() == source_layer.blobs_size() (1 vs. 2) Incompatible number of blobs for layer conv1

when I tried to run resnet-50 in BVLC caffe, but everything was ok when I run resnet-101 and resnet-152 using your model file in https://onedrive.live.com/?authkey=%21AAFW2-FVoxeVRck&id=4006CBB8476FF777%2117887&cid=4006CBB8476FF777

**Comment by TerryBryant** [comment]
@billhhh hi, have you solved the problem in resnet-50? I'm running the same problem with you
