### ISSUE TITLE
Question about visualization of the deep residual network structures.

### ISSUE THREAD

**Issue by xmubingo** [KaimingHe/deep-residual-networks#7]
Hi @KaimingHe ,

Thanks for sharing deep residual network prototxt with us. I am curious about your visualization of network structures, like http://ethereon.github.io/netscope/#/gist/db945b393d40bfa26006.

How to make these web pages? It's so useful and clear.

Thanks.

**Comment by KaimingHe** [comment]
@xmubingo the tool is from http://ethereon.github.io/netscope/quickstart.html

I have added a link in readme.

**Comment by xmubingo** [comment]
@KaimingHe  Thanks!
